/* Cuenta opcional: invitado sigue funcionando localmente; cuenta desbloquea sincronización futura. */
(function(){
  if(!window.supabase||!window.FITBLOQ_SUPABASE_URL)return;
  const client=window.supabase.createClient(window.FITBLOQ_SUPABASE_URL,window.FITBLOQ_SUPABASE_KEY);
  window.fitbloqAuth=client; state.authMode ||= 'guest';
  function accountModal(){
    client.auth.getSession().then(({data})=>{const u=data.session?.user;if(u){modal(`<span class="pill">CUENTA</span><h2 style="margin-top:14px">Tu cuenta</h2><p>${u.email||'Cuenta conectada'}</p><p class="notice">La sincronización de entrenos, dieta, Strava y Apple Health se activará en la siguiente fase.</p><button class="button secondary wide" id="signOut">Cerrar sesión</button>`);document.querySelector('#signOut').onclick=async()=>{await client.auth.signOut();state.authMode='guest';save();closeModal();home();};return;}modal(`<span class="pill">ACCESO</span><h2 style="margin-top:14px">Entrar en FitBloq</h2><p>Como invitado puedes probar todo en este dispositivo. Crea una cuenta para preparar la sincronización entre dispositivos.</p><div class="tabs"><button class="tab active" id="showLogin">Iniciar sesión</button><button class="tab" id="showSignup">Crear cuenta</button></div><div id="authForm"><label>Email<input id="authEmail" type="email" autocomplete="email" placeholder="tu@email.com"></label><label>Contraseña<input id="authPassword" type="password" autocomplete="current-password" placeholder="Mínimo 6 caracteres"></label><button class="button green wide" id="emailAuth">Iniciar sesión</button></div><div class="input-row" style="margin-top:12px"><button class="button secondary" id="googleAuth">Continuar con Google</button><button class="button secondary" id="appleAuth">Continuar con Apple</button></div><button class="tab wide" id="guestAuth">Continuar como invitado</button><p id="authMessage" class="notice"></p>`);let signup=false;const form=()=>{document.querySelector('#emailAuth').textContent=signup?'Crear cuenta':'Iniciar sesión';document.querySelector('#authMessage').textContent='';};document.querySelector('#showLogin').onclick=()=>{signup=false;form();};document.querySelector('#showSignup').onclick=()=>{signup=true;form();};document.querySelector('#emailAuth').onclick=async()=>{const email=document.querySelector('#authEmail').value.trim(),password=document.querySelector('#authPassword').value;if(password.length<6){document.querySelector('#authMessage').textContent='Usa al menos 6 caracteres.';return;}const r=signup?await client.auth.signUp({email,password}):await client.auth.signInWithPassword({email,password});if(r.error){document.querySelector('#authMessage').textContent=r.error.message;return;}state.authMode='account';save();closeModal();home();};document.querySelector('#googleAuth').onclick=()=>client.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.href}});document.querySelector('#appleAuth').onclick=()=>client.auth.signInWithOAuth({provider:'apple',options:{redirectTo:location.href}});document.querySelector('#guestAuth').onclick=()=>{state.authMode='guest';save();closeModal();home();};});
  }
  const oldBind=bind;bind=function(){oldBind();document.querySelector('.avatar')?.addEventListener('click',e=>{e.stopImmediatePropagation();accountModal();},true);};
  client.auth.onAuthStateChange((_event,session)=>{if(session){state.authMode='account';state.authEmail=session.user.email;save();}});
  bind();
})();
